version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements.dev.txt
      - pip install docker-compose==2.23.3
      - pip install docker

  pre_build:
    commands:
      - echo "Starting tests..."

  build:
    commands:
      - docker-compose run --rm app sh -c "python manage.py test"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
